plugins {
    id 'com.android.application'
}

android {
    namespace 'com.classickeys.classicplayer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.classickeys.classicplayer'
        minSdk 23 // Android 6.0
        targetSdk 35
        versionCode 1
        versionName '0.1.0-alpha'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
